/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FrmPlanning;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import model.Promotion;
import model.Sauvegarde;
import tools.Utilitaire;

/**
 *
 * @author Cynthia
 */
public class FrmIndex extends javax.swing.JFrame {

    Promotion promo;
    Sauvegarde s;

    /**
     * Creates new form FrmIndex
     */
    public FrmIndex() {
        initComponents();
        s = new Sauvegarde();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../tools/icone.gif")));
        jPnlOuvrir.setVisible(false);
        jBtnValider.setEnabled(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblBienvenue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBtnCreer = new javax.swing.JButton();
        jBtnOuvrir = new javax.swing.JButton();
        jPnlOuvrir = new javax.swing.JPanel();
        jCbxFormations = new javax.swing.JComboBox();
        jBtnValider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestionnaire de planning - Bembo Cynthia, Lada Maïlys, Long Jiani");

        jLblBienvenue.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLblBienvenue.setText("Bienvenue dans le gestionnaire de planning");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Que souhaitez-vous faire ?");

        jBtnCreer.setText("Créer une nouvelle formation");
        jBtnCreer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCreerActionPerformed(evt);
            }
        });

        jBtnOuvrir.setText("Ouvrir une formation existante");
        jBtnOuvrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOuvrirActionPerformed(evt);
            }
        });

        jBtnValider.setText("Valider");
        jBtnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnValiderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlOuvrirLayout = new javax.swing.GroupLayout(jPnlOuvrir);
        jPnlOuvrir.setLayout(jPnlOuvrirLayout);
        jPnlOuvrirLayout.setHorizontalGroup(
            jPnlOuvrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlOuvrirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jCbxFormations, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPnlOuvrirLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jBtnValider)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlOuvrirLayout.setVerticalGroup(
            jPnlOuvrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlOuvrirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCbxFormations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnValider)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLblBienvenue))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jBtnCreer, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnOuvrir, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jPnlOuvrir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLblBienvenue)
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnCreer, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jBtnOuvrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jPnlOuvrir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCreerActionPerformed
        FrmAjoutFormation frmAjForm = new FrmAjoutFormation(s);
        frmAjForm.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../tools/icone.gif")));
        frmAjForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnCreerActionPerformed

    private void jBtnOuvrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOuvrirActionPerformed
        s = Sauvegarde.deserialiser();
        if (s == null) {
            JOptionPane.showMessageDialog(null, "Une erreur est survenue: le fichier est introuvable!", "Erreur", JOptionPane.WARNING_MESSAGE);
        } else {
            if (!s.getLstPromotions().isEmpty()) {
                for (Promotion p : s.getLstPromotions()) {
                    jCbxFormations.addItem(p.getNom());
                }
            }
            jPnlOuvrir.setVisible(true);
            if (jCbxFormations.getSelectedIndex() > -1) {
                jBtnValider.setEnabled(true);
            } else {
                jBtnValider.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jBtnOuvrirActionPerformed

    private void jBtnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnValiderActionPerformed
        promo = Utilitaire.getPromotion(jCbxFormations.getSelectedItem().toString());
        //promo = Promotion.deserialiser(promo.getNom(),promo.getCalendrier().getAnnee()+"");
        FrmPlanning frmPlng = new FrmPlanning(promo, s);
        frmPlng.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../tools/icone.gif")));
        frmPlng.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnValiderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCreer;
    private javax.swing.JButton jBtnOuvrir;
    private javax.swing.JButton jBtnValider;
    private javax.swing.JComboBox jCbxFormations;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblBienvenue;
    private javax.swing.JPanel jPnlOuvrir;
    // End of variables declaration//GEN-END:variables
}
