/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.table.AbstractTableModel;
import model.*;

/**
 *
 * @author Cynthia
 */
public class PanelPlanning extends javax.swing.JPanel {

    ModeleTableau modele;
    Planning planning;
    int rang;
    ArrayList<Jour> lesJMatin;
    ArrayList<Jour> lesJSoir;

    /**
     * Creates new form PanelPlanning
     *
     * @param p
     * @param rangSemaineActive
     */
    public PanelPlanning(Planning p, int rangSemaineActive) {
        modele = new ModeleTableau();
        initComponents();
        this.planning = p;
        this.rang = rangSemaineActive;
        lesJMatin = p.getLaSemaineMatin(rang);        
        lesJSoir = p.getLaSemaineSoir(rang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabPlanning = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        tabPlanning.setModel(modele);
        jScrollPane1.setViewportView(tabPlanning);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabPlanning;
    // End of variables declaration//GEN-END:variables

    private class ModeleTableau extends AbstractTableModel {

        @Override
        public int getRowCount() {
            return 2;
        }

        @Override
        public String getColumnName(int columnIndex) {
            switch (columnIndex) {
                case 0:
                    return "Lundi";
                case 1:
                    return "Mardin";
                case 2:
                    return "Mercredi";
                case 3:
                    return "Jeudi";
                case 4:
                    return "Vendredi";
                case 5:
                    return "Samedi";
                case 6:
                    return "Dimanche";
                default:
                    return "";
            }
        }

        @Override
        public int getColumnCount() {
            return 7;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            if (rowIndex == 0)
                return lesJMatin.get(columnIndex).getSceance().getLeModule().getNom();
            else if (rowIndex == 1)
                return lesJSoir.get(columnIndex).getSceance().getLeModule().getNom();
            else
                return "";
        }
    }
}

